config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#show', as: 'profile'

  root to: 'chitoge/dashboard#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener"


  # for authentication
  get 'register' => 'auth/register#new'
  post 'register' => 'auth/register#create'

  get 'login' => 'auth/session#new'
  post 'login' => 'auth/session#create'

  post 'logout' => 'auth/session#destroy'

  get 'forget-password' => 'auth/forget_password#new'
  post 'forget-password' => 'auth/forget_password#create'

  resources :employees

  resources :leave_requests, only: [:index, :new, :create] do
    member do
      patch :approve
      patch :decline
    end
  end

  namespace :chitoge do
    # authentication
    namespace :auth do
      get 'login' => 'session#new'
      post 'login' => 'session#create'

      post 'logout' => 'session#destroy'
    end

    resources :payrolls, only: [:index, :new, :create, :show] do
      collection do
        post 'bulk_create' => 'payrolls'
      end
    end
    resources :employees do
      resources :attendances, only: [:index, :create] do
        collection do
          post 'check_in', to: 'attendances#check_in'
          post 'check_out', to: 'attendances#check_out'
        end
      end
      get 'payrolls', to: 'payrolls#employee_payrolls'
    end

    resources :attendances, only: [:index]
    resources :departments
    resources :companies do
      get "departments", to: "companies#departments"
    end
    get 'employees/index'

    get "/dashboard" => "dashboard#index"

  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  belongs_to :company
  has_many :attendances, dependent: :destroy
  has_many :leave_requests
  has_many :payrolls

  def attendance_by_date(date)
    attendances.where(checkin_time: date.beginning_of_day..date.end_of_day).first
  end

  def attendances_for_date_range(from, to)
    attendances.where(checkin_time: from.beginning_of_day..to.end_of_day)
  end

end

app/controllers/chitoge/employees_controller.rb
module Chitoge
  class EmployeesController < ApplicationController
    before_action :require_admin_authority

    def index
      @employees = Employee.with_current_company
    end

    def show
      # @leaves = LeaveRequest.all
      @employee = Employee.find_by(id: params[:id])
      @leaves = @employee.leave_requests.order(created_at: :desc)
      if @employee
        @attendances = @employee.attendances.order(created_at: :desc) # Fetch attendance records
        respond_to do |format|
          format.html
          format.json { render json: @employee }
        end
      else
        respond_to do |format|
          format.html { redirect_to chitoge_employees_path, alert: "Employee not found." }
          format.json { render json: { error: "Employee not found" }, status: :not_found }
        end
      end
    end

    def new
      @employee = Employee.new
    end

    def create
      @employee = Employee.new(employee_params.except(:password))

      @user = User.new(
        name: employee_params[:name],
        email: employee_params[:email],
        password_digest: BCrypt::Password.create(employee_params[:password]),
        company_id: employee_params[:company_id],
        role: "employee",
        last_login_at: Time.now
      )

      if @user.save! && @employee.save
        redirect_to chitoge_employees_path, notice: 'Employee was successfully created.'
      else
        render :new
      end
    end

    def edit
      @employee = Employee.find_by(id: params[:id])
      if @employee
        respond_to do |format|
          format.html
          format.json { render json: @employee }
        end
      else
        respond_to do |format|
          format.html { redirect_to chitoge_employees_path, alert: "Employee not found." }
          format.json { render json: { error: "Employee not found" }, status: :not_found }
        end
      end
    end

    def update
      @employee = Employee.find_by(id: params[:id])
      @user = User.find_by(email: @employee.email)

      if @employee && @user
        @user.name = employee_params[:name].present? ? employee_params[:name] : @user.name
        @user.email = employee_params[:email].present? ? employee_params[:email] : @user.email
        @user.password_digest = employee_params[:password].present? ?
                                  BCrypt::Password.create(employee_params[:password]) :
                                  @user.password_digest
        @user.date_of_birth = employee_params[:date_of_birth].present? ? employee_params[:date_of_birth] : @user.date_of_birth

        if @employee.update!(employee_params.except(:password)) && @user.save!
          redirect_to chitoge_employees_path, notice: 'Employee was successfully updated.'
        else
          render :edit
        end
      else
        flash[:alert] = "Employee not found."
        redirect_to chitoge_employees_path
      end
    end

    def destroy
      @employee = Employee.find(params[:id])
      @employee.destroy
      respond_to do |format|
        format.html { redirect_to chitoge_employees_path, notice: 'Employee was successfully deleted.' }
        format.json { render json: { message: "Employee was successfully deleted." }, status: :ok }
      end
    end

    def employee_params
      params
          .require(:employee)
          .permit(
            :name,
            :email,
            :phone_number,
            :job_title,
            :company_id,
            :hire_at,
            :department_id,
            :salary,
            :hourly_rate,
            :date_of_birth,
            :password,
          )
    end

    private
      def require_admin_authority
        if !current_user.company_admin?
          flash[:alert] = "You are not authorized to perform this action."
          redirect_to "/404.html"
        end
      end
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: @employee, class: "contents") do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
        <% @employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="grid md:grid-cols bg-gray-100 shadow-md rounded-lg mx-auto mt-10">
    <div class="col-sm-span-2 px-5 py-5">
      <h1 class="text-2xl text-center text-blue-500 mb-10">Employees Registration</h1>

        <div class="grid md:grid-cols-2 md:gap-6">
          <div class="relative z-0 w-full mb-5 group">
            <%= f.text_field :name, class: "form_input peer", id: "name", placeholder: " ", required: true %>
            <%= f.label :name, for: "first_name", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            <% if @employee.errors[:name].any? %>
                <p class="text-sm text-red-500">Name <%= @employee.errors[:name].first %></p>
            <% end %>
          </div>
          <div class="relative z-0 w-full mb-5 group">
            <%= f.text_field :email, class: "form_input peer", id: "email", placeholder: " ", required: true %>
            <%= f.label :email, for: "email", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            <% if @employee.errors[:email].any? %>
                <p class="text-sm text-red-500">Email<%= @employee.errors[:email].first %></p>
            <% end %>
          </div>
        </div>
        <div class="grid md:grid-cols-2 md:gap-6">
          <div class="relative z-0 w-full mb-5 group">
            <%= f.text_field :phone_number, class: "form_input peer", id: "phone_number", placeholder: " ", required: true, maxlength: 11, pattern: "[0-9]*", inputmode: "numeric", oninput: "this.value = this.value.replace(/[^0-9]/g, '')" %>
            <%= f.label :phone_number, for: "phone_number", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            <% if @employee.errors[:phone_number].any? %>
                <p class="text-sm text-red-500">PhoneNumber <%= @employee.errors[:phone_number].first %></p>
            <% end %>
          </div>
          <div class="relative z-0 w-full mb-5 group">
            <%= f.password_field :password, class: "form_input peer", id: "password", placeholder: " " %>
            <%= f.label :password, for: "password", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            <% if @employee.errors[:password].any? %>
                <p class="text-sm text-red-500">Password <%= @employee.errors[:password].first %></p>
            <% end %>
          </div>
        </div>

        <div class="grid md:grid-cols-2 md:gap-6">
            <div class="relative z-0 w-full mb-5 group">
                <%= f.text_field :job_title, class: "form_input peer", id: "job_title", placeholder: " ", required: true %>
                <%= f.label :job_title, for: "job_title", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
                <% if @employee.errors[:job_title].any? %>
                    <p class="text-sm text-red-500">Job Title<%= @employee.errors[:job_title].first %></p>
                <% end %>
            </div>

            <div class="relative z-0 w-full mb-5 group">
                <%= f.collection_select :department_id, Department.with_current_company, :id, :name, { prompt: "Select a Department" }, { class: "form_input peer", id: "company_id", required: true } %>
                <%= f.label :department_id, for: "department_at", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
                <% if @employee.errors[:department_id].any? %>
                    <p class="text-sm text-red-500">Department At<%= @employee.errors[:department_id].first %></p>
                <% end %>
            </div>
        </div>

        <div class="grid md:grid-cols-2 md:gap-6">
          <div class="relative z-0 w-full mb-5 group">
            <%= f.date_field :date_of_birth, class: "form_input peer", id: "date_of_birth", placeholder: " ", required: true %>
            <%= f.label :date_of_birth, for: "hire_at", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            <% if @employee.errors[:date_of_birth].any? %>
                <p class="text-sm text-red-500">Date of birth<%= @employee.errors[:date_of_birth].first %></p>
            <% end %>
          </div>
          <div class="relative z-0 w-full mb-5 group">
            <%= f.date_field :hire_at, class: "form_input peer", id: "hire_at", placeholder: " ", required: true %>
            <%= f.label :hire_at, for: "hire_at", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            <% if @employee.errors[:hire_at].any? %>
                <p class="text-sm text-red-500">Hire At <%= @employee.errors[:hire_at].first %></p>
            <% end %>
          </div>
        </div>

        <div class="grid md:grid-cols-2 md:gap-6">
          <div class="relative z-0 w-full mb-5 group">
            <%= f.text_field :hourly_rate, class: "form_input peer", id: "hourly_rate", placeholder: " ", required: true %>
            <%= f.label :hourly_rate, for: "hourly_rate", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            <% if @employee.errors[:hourly_rate].any? %>
                <p class="text-sm text-red-500">Date of birth<%= @employee.errors[:hourly_rate].first %></p>
            <% end %>
          </div>
          <div class="relative z-0 w-full mb-5 group">
            <%= f.text_field :salary, class: "form_input peer", id: "salary", placeholder: " ", required: true %>
            <%= f.label :salary, for: "salary", class: "form_label peer-focus:font-medium peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
            <% if @employee.errors[:salary].any? %>
                <p class="text-sm text-red-500">Hire At <%= @employee.errors[:salary].first %></p>
            <% end %>
          </div>
        </div>

          <%# submit button %>
         <div class="flex justify-end mt-10">
         <div>
           <%= link_to "Back to employees", employees_path, class: "text-black bg-gray-300 hover:bg-gray-400 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-3 text-center" %>
           <%= f.submit class: "text-white bg-blue-600 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center" %>
         </div>
        </div>
    </div>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="card">

    <%= render "form", employee: @employee %>

  </div>
</div>

app/views/employees/index.html.erb
<div>
  <% if notice.present? %>
    <p class="flex py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg text-center justify-center" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Employees" %>

  <div class="flex container justify-between items-center my-10 mx-auto">
    <h1 class="font-bold text-4xl">Employees</h1>
    <%= link_to new_employee_path, class: "rounded-lg py-2 px-3 bg-blue-600 hover:bg-blue-800 text-white block font-medium focus:ring-4 focus:ring-blue-300 flex items-center gap-2" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
      </svg>
      New Employee
    <% end %>
  </div>

  <div id="employees" class="container mx-auto">
      <!-- Delete Confirmation Modal -->
      <div id="deleteModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 hidden z-50 overflow-y-auto h-full w-full flex items-center justify-center">
        <div class="relative p-5 border w-96 shadow-lg rounded-md bg-white">
          <div class="mt-3 text-center">
            <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-red-100">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="red" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z" />
              </svg>
            </div>
            <h3 class="text-lg leading-6 font-medium text-gray-900 my-5">Are you sure you want to delete this employee?</h3>
            <p class="text-sm font-small text-gray-500 my-4">This action cannot be undone.</p>
            <div class="flex items-center px-4 py-3 justify-center space-x-4">
              <button id="cancelDelete" class="px-4 py-2 bg-gray-300 text-black rounded-md hover:bg-gray-400 focus:outline-none">
                Cancel
              </button>
              <button id="confirmDelete" class="px-4 py-2 bg-red-500 text-white rounded-md hover:bg-red-700 focus:outline-none">
                Delete
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Modal -->
    <div class="overflow-x-auto shadow-md sm:rounded-lg my-10">
      <table class="w-full text-sm text-left rtl:text-right text-gray-500 table-auto">
        <thead class="text-xs text-gray-700 uppercase bg-gray-200">
          <tr>
            <th scope="col" class="px-6 py-3">
              Name
            </th>
            <th scope="col" class="px-6 py-3">
              Email
            </th>
            <th scope="col" class="px-6 py-3">
              Phone
            </th>
            <th scope="col" class="px-6 py-3">
              Job Title
            </th>
            <th scope="col" class="px-6 py-3 text-center">
              Action
            </th>
          </tr>
        </thead>
        <tbody>
          <% if @employees.empty? %>
            <tr class="bg-white border-b">
              <td colspan="6" class="px-6 py-4 text-center text-gray-500">
                There is no employee.
              </td>
            </tr>
          <% else %>
            <% @employees.each do |employee| %>
              <tr class="bg-white border-b cursor-pointer hover:bg-gray-50" data-id="<%= employee.id %>">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                  <%= employee.name %>
                </th>
                <td class="px-6 py-4">
                  <%= employee.email %>
                </td>
                <td class="px-6 py-4">
                  <%= employee.phone_number %>
                </td>
                <td class="px-6 py-4">
                  <%= employee.job_title %>
                </td>
                <td class="flex px-6 py-4 text-center justify-center">
                  <%= link_to "Edit", edit_employee_path(employee), class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 focus:outline-none" %>
                  <button data-id="<%= employee.id %>" class="delete-button focus:outline-none text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2">
                    Delete
                  </button>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <!-- Employee Modal -->
  <div id="employeeModal" class="hidden">
    <div class="overlay"></div>
    <!-- Modal content -->
    <div id="modalContentWrapper" class="bg-white rounded-lg shadow-lg p-6 w-11/12 md:w-1/2 z-50 transform opacity-0 -translate-y-10 transition-all duration-300 ease-in-out">
      <button id="closeModal" class="float-right text-gray-500 hover:text-gray-700 focus:outline-none">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
      <h2 class="text-xl font-bold mb-4 text-center">Employee Details</h2>
      <div id="modalContent">
        <!-- Employee details will be dynamically loaded here -->
      </div>
    </div>
  </div>
  <!-- End Modal -->
</div>


<%= javascript_include_tag 'employee' %>

app/views/employees/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="card">

    <%= render "form", employee: @employee %>

  </div>
</div>